version: "3.3"
services:
    sql:
        build: .
        ports:
            - "3306:3306"
        volumes:
            - myVol:/var/lib/mysql
        env_file:
            - config.txt
        container_name: sql
            
        restart: always
        
    gatewayms:
        image: gatewayms
        ports:
            - "4001:4001"
            
        env_file:
            - config.txt
            
        depends_on:
            - sql
    userms:
        image: userms
        ports:
            - "8070:8070"
        env_file:
            - config.txt
            
        depends_on:
            - gatewayms
        
        
    transactionms:
        image: transactionms
        ports:
            - "8073:8073"
        env_file:
            - config.txt
        
        depends_on:
            - gatewayms
        
    bankms:
        image: bankms
        ports:
            - "8083:8083"
        env_file:
            - config.txt
        
        depends_on:
            - gatewayms
        
    underwriterms:
        image: underwriterms
        ports:
            - "8071:8071"
        env_file:
            - config.txt
        
        depends_on:
            - gatewayms
        
volumes:
    myVol:
        #external: #swarm stuff
           #name: alineService_myVol #swarm stuff
    
    
    

    
    
    
        